#pragma once

enum ConfigKey
{
	//common
	CONFIG_KEY_LOGIN_MODLE = 0,								// see LoginModle
	CONFIG_KEY_MIN_CODERATE = 11,							//主播单路最小上行码率
	CONFIG_KEY_MAX_CODERATE = 12,							//主播单路最大上行码率
	CONFIG_KEY_TOTAL_CODERATE = 13,							//主播上行多路时总码率限制
	CONFIG_KEY_CUR_CODERATE = 14,							//主播上行控制起始码率
	CONFIG_KEY_USE_CRCONTROL = 15,							//主播上行是否使用码率控制

	//video
	CONFIG_KEY_VIDEO_BEGIN = 100,
	CONFIG_KEY_VIDEO_RECORD_QUALITY = 101,					// see VideoQualityMode
	CONFIG_KEY_VIDEO_ENCODE_WIDTH = 102,					// see VIDEO_ENCODE_SIZES for what size support
	CONFIG_KEY_VIDEO_ENCODE_HEIGHT = 103,					// see VIDEO_ENCODE_SIZES for what size support
	CONFIG_KEY_VIDEO_ENCODE_FRAMERATE = 104,
	CONFIG_KEY_VIDEO_ENCODE_BITRATE = 105,
	CONFIG_KEY_VIDEO_MIN_BUFFER = 106,
	CONFIG_KEY_VIDEO_DEFAULT_CAMERA =107, 					// 设置默认摄像头(front/back)
	CONFIG_KEY_VIDEO_HIGHDEFINITION_OR_LOWLATENCY = 108,	// 0是高画质，1是低延时
	CONFIG_KEY_VIDEO_RESOLUTION_WIDTH = 109,
	CONFIG_KEY_VIDEO_RESOLUTION_HEIGHT = 110,


    CONFIG_KEY_VIDEO_ENCODE_PRESET = 121, // see VideoEncodePreset
    CONFIG_KEY_VIDEO_HARDWARE_ENCODE = 122,
    CONFIG_KEY_VIDEO_HARDWARE_DECODE = 123,
	CONFIG_KEY_VIDEO_END = 199,

	//audio
	CONFIG_KEY_AUDIO_BEGIN = 200,
	CONFIG_KEY_AUDIO_RECORD_QUALITY = 201,
	CONFIG_KEY_AUDIO_MIN_BUFFER = 202,
	CONFIG_KEY_AUDIO_VOICE_PROCESSING = 203,
	CONFIG_KEY_AUDIO_END = 299,
	CONFIG_KEY_AUDIO_MODE = 300,
};

enum LoginModle
{
    LOGIN_MODULE_CHANNEL = 0,
    LOGIN_MODULE_LOWLATENCY, //lowlatency mode,maybe 1 v n.
    LOGIN_MODULE_LOWLATENCY_1V1 //lowlatency and just 1v1.
};

enum CameraType
{
	CAMERA_TYPE_FRONT = 0,
	CAMERA_TYPE_BACK,
};

enum VideoQualityMode
{
	VIDEO_QUALITY_LOW = 0,
	VIDEO_QUALITY_MEDIUM,
	VIDEO_QUALITY_HIGHT,
	VIDEO_QUALITY_UNKNOW,
	VIDEO_QUALITY_CUSTOM,
};

enum VideoEncodePreset
{
    VIDEO_ENCODE_PRESET_DEFAULT = 0,
    VIDEO_ENCODE_PRESET_ULTRAFAST,
    VIDEO_ENCODE_PRESET_SUPERFAST,
    VIDEO_ENCODE_PRESET_VERYFAST,
    VIDEO_ENCODE_PRESET_FASTER,
    VIDEO_ENCODE_PRESET_FAST,
    VIDEO_ENCODE_PRESET_MEDIUM,
    VIDEO_ENCODE_PRESET_SLOW,
};

enum AudioQualityMode
{
	AUDIO_QUALITY_LOW = 0,
	AUDIO_QUALITY_MEDIUM,
	AUDIO_QUALITY_HIGHT,
	AUDIO_QUALITY_UNKNOW,
	AUDIO_QUALITY_CUSTOM,
	AUDIO_QUALITY_MUSIC,
};

#define VIDEO_QUALITY_LOW	VIDEO_QUALITY_LOW_LATENCY

const int kDefaultMinBuffer = 4000;
const uint32_t kVideoHightQualityBuffer = 2000;
const uint32_t kVideoLowLatencyBuffer = 500; //避免测试安卓语音丢包
